* Implementar la creación de panoramas lineales con proyección en superficies cilíndricas
o esféricas y mezcla de colores usando el algoritmo de Burt-Adelson. (25 puntos)

Podemos hacer las dos proyecciones, y ver las diferencias entre ellas.
En la proyección cilíndrica, hay que contemplar que solo dibuje una
vez la image, ya que cuando la distancia focal es corta (depende) del
tamaño de la imagen, no lo hace bien. Escogeremos la proyección esferica
que introduce menos deformación global, para hacer el mosaico. El mosaico
no está hecho aún, falta arreglar los huecos negros que introduce cuando
genera el mosaico. Lo que falla es el lado izquierdo del mosaico, el
derecho creo que lo genera bien.
- Mosaico Facultad con distancia focal 200.
- Mosaico Guernica con distancia focal 700.

** Pasos del algoritmo

1. Realizar proyecciones cilíndricas
2. Encontrar los puntos SIFT y las homografías para hacer el mosaico
   (tal como se hizo en la práctica) sobre las imágenes proyectadas.
3. Corregir el color usando el algoritmo de Burt-Adelson,
   para ello tenemos que hacer la pirámide Laplaciana
   (tema 4 "7.Panoramas", página 24 y 57)

*** Proyección cilíndrica
No sé muy bien por qué hay que hacer esto. Quizá cuando se está
tratando de hacer un mosaico de una imagen que abarca un ángulo
muy grande se notan muchos las distorsiones a menos que se proyecten
las fotos sobre una superficie cilíndrica.
(arreglar cuando la distancia focal es pequeña)

En principio está hecha. Habría que ver cómo hacer la proyección
sobre la esfera pero debe ser fácil.

*** Proyección esférica
Respuesta del profesor: Valoraré lo que hagais. En principio si
elegis una mejor la esferica que introduce menos deformación global.

*** Encontrar puntos SIFT
Mirar función de "mosaicoN()"

*** Corrección del color
Esta es la parte gorda del trabajo imagino.


**** Referencias:
http://persci.mit.edu/pub_pdfs/spline83.pdf
https://www.cse.wustl.edu/~furukawa/cse559a/2016_fall/notes/06-1-stitching.pdf
https://www.compuphase.com/panorama.pdf

